#pragma once

#include <Windows.h>
#include <GL/GL.h>
#include <GL/wgl.h>
#include <GL/wglext.h>

#define DECLARE_WGL_FUNCTION(type, name) extern type name;

extern "C"
{
#ifdef WGL_3DL_stereo_control
	DECLARE_WGL_FUNCTION(PFNWGLSETSTEREOEMITTERSTATE3DLPROC, wglSetStereoEmitterState3DL)
#endif

#ifdef WGL_AMD_gpu_association
	DECLARE_WGL_FUNCTION(PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC,         wglBlitContextFramebufferAMD)
	DECLARE_WGL_FUNCTION(PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC,        wglCreateAssociatedContextAMD)
	DECLARE_WGL_FUNCTION(PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC, wglCreateAssociatedContextAttribsAMD)
	DECLARE_WGL_FUNCTION(PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC,        wglDeleteAssociatedContextAMD)
	DECLARE_WGL_FUNCTION(PFNWGLGETCONTEXTGPUIDAMDPROC,                wglGetContextGPUIDAMD)
	DECLARE_WGL_FUNCTION(PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC,    wglGetCurrentAssociatedContextAMD)
	DECLARE_WGL_FUNCTION(PFNWGLGETGPUIDSAMDPROC,                      wglGetGPUIDsAMD)
	DECLARE_WGL_FUNCTION(PFNWGLGETGPUINFOAMDPROC,                     wglGetGPUInfoAMD)
	DECLARE_WGL_FUNCTION(PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC,   wglMakeAssociatedContextCurrentAMD)
#endif

#ifdef WGL_ARB_buffer_region
	DECLARE_WGL_FUNCTION(PFNWGLCREATEBUFFERREGIONARBPROC,  wglCreateBufferRegionARB)
	DECLARE_WGL_FUNCTION(PFNWGLDELETEBUFFERREGIONARBPROC,  wglDeleteBufferRegionARB)
	DECLARE_WGL_FUNCTION(PFNWGLRESTOREBUFFERREGIONARBPROC, wglRestoreBufferRegionARB)
	DECLARE_WGL_FUNCTION(PFNWGLSAVEBUFFERREGIONARBPROC,    wglSaveBufferRegionARB)
#endif

#ifdef WGL_ARB_create_context
	DECLARE_WGL_FUNCTION(PFNWGLCREATECONTEXTATTRIBSARBPROC, wglCreateContextAttribsARB)
#endif

#ifdef WGL_ARB_extensions_string
	DECLARE_WGL_FUNCTION(PFNWGLGETEXTENSIONSSTRINGARBPROC, wglGetExtensionsStringARB)
#endif

#ifdef WGL_ARB_make_current_read
	DECLARE_WGL_FUNCTION(PFNWGLGETCURRENTREADDCARBPROC,   wglGetCurrentReadDCARB)
	DECLARE_WGL_FUNCTION(PFNWGLMAKECONTEXTCURRENTARBPROC, wglMakeContextCurrentARB)
#endif

#ifdef WGL_ARB_pbuffer
	DECLARE_WGL_FUNCTION(PFNWGLCREATEPBUFFERARBPROC,    wglCreatePbufferARB)
	DECLARE_WGL_FUNCTION(PFNWGLDESTROYPBUFFERARBPROC,   wglDestroyPbufferARB)
	DECLARE_WGL_FUNCTION(PFNWGLGETPBUFFERDCARBPROC,     wglGetPbufferDCARB)
	DECLARE_WGL_FUNCTION(PFNWGLQUERYPBUFFERARBPROC,     wglQueryPbufferARB)
	DECLARE_WGL_FUNCTION(PFNWGLRELEASEPBUFFERDCARBPROC, wglReleasePbufferDCARB)
#endif

#ifdef WGL_ARB_pixel_format
	DECLARE_WGL_FUNCTION(PFNWGLCHOOSEPIXELFORMATARBPROC,      wglChoosePixelFormatARB)
	DECLARE_WGL_FUNCTION(PFNWGLGETPIXELFORMATATTRIBFVARBPROC, wglGetPixelFormatAttribfvARB)
	DECLARE_WGL_FUNCTION(PFNWGLGETPIXELFORMATATTRIBIVARBPROC, wglGetPixelFormatAttribivARB)
#endif

#ifdef WGL_ARB_render_texture
	DECLARE_WGL_FUNCTION(PFNWGLBINDTEXIMAGEARBPROC,     wglBindTexImageARB)
	DECLARE_WGL_FUNCTION(PFNWGLRELEASETEXIMAGEARBPROC,  wglReleaseTexImageARB)
	DECLARE_WGL_FUNCTION(PFNWGLSETPBUFFERATTRIBARBPROC, wglSetPbufferAttribARB)
#endif

#ifdef WGL_EXT_display_color_table
	DECLARE_WGL_FUNCTION(PFNWGLBINDDISPLAYCOLORTABLEEXTPROC,    wglBindDisplayColorTableEXT)
	DECLARE_WGL_FUNCTION(PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC,  wglCreateDisplayColorTableEXT)
	DECLARE_WGL_FUNCTION(PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC, wglDestroyDisplayColorTableEXT)
	DECLARE_WGL_FUNCTION(PFNWGLLOADDISPLAYCOLORTABLEEXTPROC,    wglLoadDisplayColorTableEXT)
#endif

#ifdef WGL_EXT_extensions_string
	DECLARE_WGL_FUNCTION(PFNWGLGETEXTENSIONSSTRINGEXTPROC, wglGetExtensionsStringEXT)
#endif

#ifdef WGL_EXT_make_current_read
	DECLARE_WGL_FUNCTION(PFNWGLGETCURRENTREADDCEXTPROC,   wglGetCurrentReadDCEXT)
	DECLARE_WGL_FUNCTION(PFNWGLMAKECONTEXTCURRENTEXTPROC, wglMakeContextCurrentEXT)
#endif

#ifdef WGL_EXT_pbuffer
	DECLARE_WGL_FUNCTION(PFNWGLCREATEPBUFFEREXTPROC,    wglCreatePbufferEXT)
	DECLARE_WGL_FUNCTION(PFNWGLDESTROYPBUFFEREXTPROC,   wglDestroyPbufferEXT)
	DECLARE_WGL_FUNCTION(PFNWGLGETPBUFFERDCEXTPROC,     wglGetPbufferDCEXT)
	DECLARE_WGL_FUNCTION(PFNWGLQUERYPBUFFEREXTPROC,     wglQueryPbufferEXT)
	DECLARE_WGL_FUNCTION(PFNWGLRELEASEPBUFFERDCEXTPROC, wglReleasePbufferDCEXT)
#endif

#ifdef WGL_EXT_pixel_format
	DECLARE_WGL_FUNCTION(PFNWGLCHOOSEPIXELFORMATEXTPROC,      wglChoosePixelFormatEXT)
	DECLARE_WGL_FUNCTION(PFNWGLGETPIXELFORMATATTRIBFVEXTPROC, wglGetPixelFormatAttribfvEXT)
	DECLARE_WGL_FUNCTION(PFNWGLGETPIXELFORMATATTRIBIVEXTPROC, wglGetPixelFormatAttribivEXT)
#endif

#ifdef WGL_EXT_swap_control
	DECLARE_WGL_FUNCTION(PFNWGLGETSWAPINTERVALEXTPROC, wglGetSwapIntervalEXT)
	DECLARE_WGL_FUNCTION(PFNWGLSWAPINTERVALEXTPROC,    wglSwapIntervalEXT)
#endif

#ifdef WGL_I3D_digital_video_control
	DECLARE_WGL_FUNCTION(PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC, wglGetDigitalVideoParametersI3D)
	DECLARE_WGL_FUNCTION(PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC, wglSetDigitalVideoParametersI3D)
#endif

#ifdef WGL_I3D_gamma
	DECLARE_WGL_FUNCTION(PFNWGLGETGAMMATABLEI3DPROC,           wglGetGammaTableI3D)
	DECLARE_WGL_FUNCTION(PFNWGLGETGAMMATABLEPARAMETERSI3DPROC, wglGetGammaTableParametersI3D)
	DECLARE_WGL_FUNCTION(PFNWGLSETGAMMATABLEI3DPROC,           wglSetGammaTableI3D)
	DECLARE_WGL_FUNCTION(PFNWGLSETGAMMATABLEPARAMETERSI3DPROC, wglSetGammaTableParametersI3D)
#endif

#ifdef WGL_I3D_genlock
	DECLARE_WGL_FUNCTION(PFNWGLDISABLEGENLOCKI3DPROC,             wglDisableGenlockI3D)
	DECLARE_WGL_FUNCTION(PFNWGLENABLEGENLOCKI3DPROC,              wglEnableGenlockI3D)
	DECLARE_WGL_FUNCTION(PFNWGLGENLOCKSAMPLERATEI3DPROC,          wglGenlockSampleRateI3D)
	DECLARE_WGL_FUNCTION(PFNWGLGENLOCKSOURCEDELAYI3DPROC,         wglGenlockSourceDelayI3D)
	DECLARE_WGL_FUNCTION(PFNWGLGENLOCKSOURCEEDGEI3DPROC,          wglGenlockSourceEdgeI3D)
	DECLARE_WGL_FUNCTION(PFNWGLGENLOCKSOURCEI3DPROC,              wglGenlockSourceI3D)
	DECLARE_WGL_FUNCTION(PFNWGLGETGENLOCKSAMPLERATEI3DPROC,       wglGetGenlockSampleRateI3D)
	DECLARE_WGL_FUNCTION(PFNWGLGETGENLOCKSOURCEDELAYI3DPROC,      wglGetGenlockSourceDelayI3D)
	DECLARE_WGL_FUNCTION(PFNWGLGETGENLOCKSOURCEEDGEI3DPROC,       wglGetGenlockSourceEdgeI3D)
	DECLARE_WGL_FUNCTION(PFNWGLGETGENLOCKSOURCEI3DPROC,           wglGetGenlockSourceI3D)
	DECLARE_WGL_FUNCTION(PFNWGLISENABLEDGENLOCKI3DPROC,           wglIsEnabledGenlockI3D)
	DECLARE_WGL_FUNCTION(PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC, wglQueryGenlockMaxSourceDelayI3D)
#endif

#ifdef WGL_I3D_image_buffer
	DECLARE_WGL_FUNCTION(PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC, wglAssociateImageBufferEventsI3D)
	DECLARE_WGL_FUNCTION(PFNWGLCREATEIMAGEBUFFERI3DPROC,          wglCreateImageBufferI3D)
	DECLARE_WGL_FUNCTION(PFNWGLDESTROYIMAGEBUFFERI3DPROC,         wglDestroyImageBufferI3D)
	DECLARE_WGL_FUNCTION(PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC,   wglReleaseImageBufferEventsI3D)
#endif

#ifdef WGL_I3D_swap_frame_lock
	DECLARE_WGL_FUNCTION(PFNWGLDISABLEFRAMELOCKI3DPROC,     wglDisableFrameLockI3D)
	DECLARE_WGL_FUNCTION(PFNWGLENABLEFRAMELOCKI3DPROC,      wglEnableFrameLockI3D)
	DECLARE_WGL_FUNCTION(PFNWGLISENABLEDFRAMELOCKI3DPROC,   wglIsEnabledFrameLockI3D)
	DECLARE_WGL_FUNCTION(PFNWGLQUERYFRAMELOCKMASTERI3DPROC, wglQueryFrameLockMasterI3D)
#endif

#ifdef WGL_I3D_swap_frame_usage
	DECLARE_WGL_FUNCTION(PFNWGLBEGINFRAMETRACKINGI3DPROC, wglBeginFrameTrackingI3D)
	DECLARE_WGL_FUNCTION(PFNWGLENDFRAMETRACKINGI3DPROC,   wglEndFrameTrackingI3D)
	DECLARE_WGL_FUNCTION(PFNWGLGETFRAMEUSAGEI3DPROC,      wglGetFrameUsageI3D)
	DECLARE_WGL_FUNCTION(PFNWGLQUERYFRAMETRACKINGI3DPROC, wglQueryFrameTrackingI3D)
#endif

#ifdef WGL_NV_DX_interop
	DECLARE_WGL_FUNCTION(PFNWGLDXCLOSEDEVICENVPROC,            wglDXCloseDeviceNV)
	DECLARE_WGL_FUNCTION(PFNWGLDXLOCKOBJECTSNVPROC,            wglDXLockObjectsNV)
	DECLARE_WGL_FUNCTION(PFNWGLDXOBJECTACCESSNVPROC,           wglDXObjectAccessNV)
	DECLARE_WGL_FUNCTION(PFNWGLDXOPENDEVICENVPROC,             wglDXOpenDeviceNV)
	DECLARE_WGL_FUNCTION(PFNWGLDXREGISTEROBJECTNVPROC,         wglDXRegisterObjectNV)
	DECLARE_WGL_FUNCTION(PFNWGLDXSETRESOURCESHAREHANDLENVPROC, wglDXSetResourceShareHandleNV)
	DECLARE_WGL_FUNCTION(PFNWGLDXUNLOCKOBJECTSNVPROC,          wglDXUnlockObjectsNV)
	DECLARE_WGL_FUNCTION(PFNWGLDXUNREGISTEROBJECTNVPROC,       wglDXUnregisterObjectNV)
#endif

#ifdef WGL_NV_copy_image
	DECLARE_WGL_FUNCTION(PFNWGLCOPYIMAGESUBDATANVPROC, wglCopyImageSubDataNV)
#endif

#ifdef WGL_NV_delay_before_swap
	DECLARE_WGL_FUNCTION(PFNWGLDELAYBEFORESWAPNVPROC, wglDelayBeforeSwapNV)
#endif

#ifdef WGL_NV_gpu_affinity
	DECLARE_WGL_FUNCTION(PFNWGLCREATEAFFINITYDCNVPROC,       wglCreateAffinityDCNV)
	DECLARE_WGL_FUNCTION(PFNWGLDELETEDCNVPROC,               wglDeleteDCNV)
	DECLARE_WGL_FUNCTION(PFNWGLENUMGPUDEVICESNVPROC,         wglEnumGpuDevicesNV)
	DECLARE_WGL_FUNCTION(PFNWGLENUMGPUSFROMAFFINITYDCNVPROC, wglEnumGpusFromAffinityDCNV)
	DECLARE_WGL_FUNCTION(PFNWGLENUMGPUSNVPROC,               wglEnumGpusNV)
#endif

#ifdef WGL_NV_present_video
	DECLARE_WGL_FUNCTION(PFNWGLBINDVIDEODEVICENVPROC,       wglBindVideoDeviceNV)
	DECLARE_WGL_FUNCTION(PFNWGLENUMERATEVIDEODEVICESNVPROC, wglEnumerateVideoDevicesNV)
	DECLARE_WGL_FUNCTION(PFNWGLQUERYCURRENTCONTEXTNVPROC,   wglQueryCurrentContextNV)
#endif

#ifdef WGL_NV_swap_group
	DECLARE_WGL_FUNCTION(PFNWGLBINDSWAPBARRIERNVPROC,    wglBindSwapBarrierNV)
	DECLARE_WGL_FUNCTION(PFNWGLJOINSWAPGROUPNVPROC,      wglJoinSwapGroupNV)
	DECLARE_WGL_FUNCTION(PFNWGLQUERYFRAMECOUNTNVPROC,    wglQueryFrameCountNV)
	DECLARE_WGL_FUNCTION(PFNWGLQUERYMAXSWAPGROUPSNVPROC, wglQueryMaxSwapGroupsNV)
	DECLARE_WGL_FUNCTION(PFNWGLQUERYSWAPGROUPNVPROC,     wglQuerySwapGroupNV)
	DECLARE_WGL_FUNCTION(PFNWGLRESETFRAMECOUNTNVPROC,    wglResetFrameCountNV)
#endif

#ifdef WGL_NV_vertex_array_range
	DECLARE_WGL_FUNCTION(PFNWGLALLOCATEMEMORYNVPROC, wglAllocateMemoryNV)
	DECLARE_WGL_FUNCTION(PFNWGLFREEMEMORYNVPROC,     wglFreeMemoryNV)
#endif

#ifdef WGL_NV_video_capture
	DECLARE_WGL_FUNCTION(PFNWGLBINDVIDEOCAPTUREDEVICENVPROC,       wglBindVideoCaptureDeviceNV)
	DECLARE_WGL_FUNCTION(PFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC, wglEnumerateVideoCaptureDevicesNV)
	DECLARE_WGL_FUNCTION(PFNWGLLOCKVIDEOCAPTUREDEVICENVPROC,       wglLockVideoCaptureDeviceNV)
	DECLARE_WGL_FUNCTION(PFNWGLQUERYVIDEOCAPTUREDEVICENVPROC,      wglQueryVideoCaptureDeviceNV)
	DECLARE_WGL_FUNCTION(PFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC,    wglReleaseVideoCaptureDeviceNV)
#endif

#ifdef WGL_NV_video_output
	DECLARE_WGL_FUNCTION(PFNWGLBINDVIDEOIMAGENVPROC,     wglBindVideoImageNV)
	DECLARE_WGL_FUNCTION(PFNWGLGETVIDEODEVICENVPROC,     wglGetVideoDeviceNV)
	DECLARE_WGL_FUNCTION(PFNWGLGETVIDEOINFONVPROC,       wglGetVideoInfoNV)
	DECLARE_WGL_FUNCTION(PFNWGLRELEASEVIDEODEVICENVPROC, wglReleaseVideoDeviceNV)
	DECLARE_WGL_FUNCTION(PFNWGLRELEASEVIDEOIMAGENVPROC,  wglReleaseVideoImageNV)
	DECLARE_WGL_FUNCTION(PFNWGLSENDPBUFFERTOVIDEONVPROC, wglSendPbufferToVideoNV)
#endif

#ifdef WGL_OML_sync_control
	DECLARE_WGL_FUNCTION(PFNWGLGETMSCRATEOMLPROC,          wglGetMscRateOML)
	DECLARE_WGL_FUNCTION(PFNWGLGETSYNCVALUESOMLPROC,       wglGetSyncValuesOML)
	DECLARE_WGL_FUNCTION(PFNWGLSWAPBUFFERSMSCOMLPROC,      wglSwapBuffersMscOML)
	DECLARE_WGL_FUNCTION(PFNWGLSWAPLAYERBUFFERSMSCOMLPROC, wglSwapLayerBuffersMscOML)
	DECLARE_WGL_FUNCTION(PFNWGLWAITFORMSCOMLPROC,          wglWaitForMscOML)
	DECLARE_WGL_FUNCTION(PFNWGLWAITFORSBCOMLPROC,          wglWaitForSbcOML)
#endif
}