#include "OGLFunctionsWin32.hpp"

#define DEFINE_WGL_FUNCTION(type, name) type name = nullptr;

extern "C"
{
#ifdef WGL_3DL_stereo_control
	DEFINE_WGL_FUNCTION(PFNWGLSETSTEREOEMITTERSTATE3DLPROC, wglSetStereoEmitterState3DL)
#endif

#ifdef WGL_AMD_gpu_association
	DEFINE_WGL_FUNCTION(PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC,         wglBlitContextFramebufferAMD)
	DEFINE_WGL_FUNCTION(PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC,        wglCreateAssociatedContextAMD)
	DEFINE_WGL_FUNCTION(PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC, wglCreateAssociatedContextAttribsAMD)
	DEFINE_WGL_FUNCTION(PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC,        wglDeleteAssociatedContextAMD)
	DEFINE_WGL_FUNCTION(PFNWGLGETCONTEXTGPUIDAMDPROC,                wglGetContextGPUIDAMD)
	DEFINE_WGL_FUNCTION(PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC,    wglGetCurrentAssociatedContextAMD)
	DEFINE_WGL_FUNCTION(PFNWGLGETGPUIDSAMDPROC,                      wglGetGPUIDsAMD)
	DEFINE_WGL_FUNCTION(PFNWGLGETGPUINFOAMDPROC,                     wglGetGPUInfoAMD)
	DEFINE_WGL_FUNCTION(PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC,   wglMakeAssociatedContextCurrentAMD)
#endif

#ifdef WGL_ARB_buffer_region
	DEFINE_WGL_FUNCTION(PFNWGLCREATEBUFFERREGIONARBPROC,  wglCreateBufferRegionARB)
	DEFINE_WGL_FUNCTION(PFNWGLDELETEBUFFERREGIONARBPROC,  wglDeleteBufferRegionARB)
	DEFINE_WGL_FUNCTION(PFNWGLRESTOREBUFFERREGIONARBPROC, wglRestoreBufferRegionARB)
	DEFINE_WGL_FUNCTION(PFNWGLSAVEBUFFERREGIONARBPROC,    wglSaveBufferRegionARB)
#endif

#ifdef WGL_ARB_create_context
	DEFINE_WGL_FUNCTION(PFNWGLCREATECONTEXTATTRIBSARBPROC, wglCreateContextAttribsARB)
#endif

#ifdef WGL_ARB_extensions_string
	DEFINE_WGL_FUNCTION(PFNWGLGETEXTENSIONSSTRINGARBPROC, wglGetExtensionsStringARB)
#endif

#ifdef WGL_ARB_make_current_read
	DEFINE_WGL_FUNCTION(PFNWGLGETCURRENTREADDCARBPROC,   wglGetCurrentReadDCARB)
	DEFINE_WGL_FUNCTION(PFNWGLMAKECONTEXTCURRENTARBPROC, wglMakeContextCurrentARB)
#endif

#ifdef WGL_ARB_pbuffer
	DEFINE_WGL_FUNCTION(PFNWGLCREATEPBUFFERARBPROC,    wglCreatePbufferARB)
	DEFINE_WGL_FUNCTION(PFNWGLDESTROYPBUFFERARBPROC,   wglDestroyPbufferARB)
	DEFINE_WGL_FUNCTION(PFNWGLGETPBUFFERDCARBPROC,     wglGetPbufferDCARB)
	DEFINE_WGL_FUNCTION(PFNWGLQUERYPBUFFERARBPROC,     wglQueryPbufferARB)
	DEFINE_WGL_FUNCTION(PFNWGLRELEASEPBUFFERDCARBPROC, wglReleasePbufferDCARB)
#endif

#ifdef WGL_ARB_pixel_format
	DEFINE_WGL_FUNCTION(PFNWGLCHOOSEPIXELFORMATARBPROC,      wglChoosePixelFormatARB)
	DEFINE_WGL_FUNCTION(PFNWGLGETPIXELFORMATATTRIBFVARBPROC, wglGetPixelFormatAttribfvARB)
	DEFINE_WGL_FUNCTION(PFNWGLGETPIXELFORMATATTRIBIVARBPROC, wglGetPixelFormatAttribivARB)
#endif

#ifdef WGL_ARB_render_texture
	DEFINE_WGL_FUNCTION(PFNWGLBINDTEXIMAGEARBPROC,     wglBindTexImageARB)
	DEFINE_WGL_FUNCTION(PFNWGLRELEASETEXIMAGEARBPROC,  wglReleaseTexImageARB)
	DEFINE_WGL_FUNCTION(PFNWGLSETPBUFFERATTRIBARBPROC, wglSetPbufferAttribARB)
#endif

#ifdef WGL_EXT_display_color_table
	DEFINE_WGL_FUNCTION(PFNWGLBINDDISPLAYCOLORTABLEEXTPROC,    wglBindDisplayColorTableEXT)
	DEFINE_WGL_FUNCTION(PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC,  wglCreateDisplayColorTableEXT)
	DEFINE_WGL_FUNCTION(PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC, wglDestroyDisplayColorTableEXT)
	DEFINE_WGL_FUNCTION(PFNWGLLOADDISPLAYCOLORTABLEEXTPROC,    wglLoadDisplayColorTableEXT)
#endif

#ifdef WGL_EXT_extensions_string
	DEFINE_WGL_FUNCTION(PFNWGLGETEXTENSIONSSTRINGEXTPROC, wglGetExtensionsStringEXT)
#endif

#ifdef WGL_EXT_make_current_read
	DEFINE_WGL_FUNCTION(PFNWGLGETCURRENTREADDCEXTPROC,   wglGetCurrentReadDCEXT)
	DEFINE_WGL_FUNCTION(PFNWGLMAKECONTEXTCURRENTEXTPROC, wglMakeContextCurrentEXT)
#endif

#ifdef WGL_EXT_pbuffer
	DEFINE_WGL_FUNCTION(PFNWGLCREATEPBUFFEREXTPROC,    wglCreatePbufferEXT)
	DEFINE_WGL_FUNCTION(PFNWGLDESTROYPBUFFEREXTPROC,   wglDestroyPbufferEXT)
	DEFINE_WGL_FUNCTION(PFNWGLGETPBUFFERDCEXTPROC,     wglGetPbufferDCEXT)
	DEFINE_WGL_FUNCTION(PFNWGLQUERYPBUFFEREXTPROC,     wglQueryPbufferEXT)
	DEFINE_WGL_FUNCTION(PFNWGLRELEASEPBUFFERDCEXTPROC, wglReleasePbufferDCEXT)
#endif

#ifdef WGL_EXT_pixel_format
	DEFINE_WGL_FUNCTION(PFNWGLCHOOSEPIXELFORMATEXTPROC,      wglChoosePixelFormatEXT)
	DEFINE_WGL_FUNCTION(PFNWGLGETPIXELFORMATATTRIBFVEXTPROC, wglGetPixelFormatAttribfvEXT)
	DEFINE_WGL_FUNCTION(PFNWGLGETPIXELFORMATATTRIBIVEXTPROC, wglGetPixelFormatAttribivEXT)
#endif

#ifdef WGL_EXT_swap_control
	DEFINE_WGL_FUNCTION(PFNWGLGETSWAPINTERVALEXTPROC, wglGetSwapIntervalEXT)
	DEFINE_WGL_FUNCTION(PFNWGLSWAPINTERVALEXTPROC,    wglSwapIntervalEXT)
#endif

#ifdef WGL_I3D_digital_video_control
	DEFINE_WGL_FUNCTION(PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC, wglGetDigitalVideoParametersI3D)
	DEFINE_WGL_FUNCTION(PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC, wglSetDigitalVideoParametersI3D)
#endif

#ifdef WGL_I3D_gamma
	DEFINE_WGL_FUNCTION(PFNWGLGETGAMMATABLEI3DPROC,           wglGetGammaTableI3D)
	DEFINE_WGL_FUNCTION(PFNWGLGETGAMMATABLEPARAMETERSI3DPROC, wglGetGammaTableParametersI3D)
	DEFINE_WGL_FUNCTION(PFNWGLSETGAMMATABLEI3DPROC,           wglSetGammaTableI3D)
	DEFINE_WGL_FUNCTION(PFNWGLSETGAMMATABLEPARAMETERSI3DPROC, wglSetGammaTableParametersI3D)
#endif

#ifdef WGL_I3D_genlock
	DEFINE_WGL_FUNCTION(PFNWGLDISABLEGENLOCKI3DPROC,             wglDisableGenlockI3D)
	DEFINE_WGL_FUNCTION(PFNWGLENABLEGENLOCKI3DPROC,              wglEnableGenlockI3D)
	DEFINE_WGL_FUNCTION(PFNWGLGENLOCKSAMPLERATEI3DPROC,          wglGenlockSampleRateI3D)
	DEFINE_WGL_FUNCTION(PFNWGLGENLOCKSOURCEDELAYI3DPROC,         wglGenlockSourceDelayI3D)
	DEFINE_WGL_FUNCTION(PFNWGLGENLOCKSOURCEEDGEI3DPROC,          wglGenlockSourceEdgeI3D)
	DEFINE_WGL_FUNCTION(PFNWGLGENLOCKSOURCEI3DPROC,              wglGenlockSourceI3D)
	DEFINE_WGL_FUNCTION(PFNWGLGETGENLOCKSAMPLERATEI3DPROC,       wglGetGenlockSampleRateI3D)
	DEFINE_WGL_FUNCTION(PFNWGLGETGENLOCKSOURCEDELAYI3DPROC,      wglGetGenlockSourceDelayI3D)
	DEFINE_WGL_FUNCTION(PFNWGLGETGENLOCKSOURCEEDGEI3DPROC,       wglGetGenlockSourceEdgeI3D)
	DEFINE_WGL_FUNCTION(PFNWGLGETGENLOCKSOURCEI3DPROC,           wglGetGenlockSourceI3D)
	DEFINE_WGL_FUNCTION(PFNWGLISENABLEDGENLOCKI3DPROC,           wglIsEnabledGenlockI3D)
	DEFINE_WGL_FUNCTION(PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC, wglQueryGenlockMaxSourceDelayI3D)
#endif

#ifdef WGL_I3D_image_buffer
	DEFINE_WGL_FUNCTION(PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC, wglAssociateImageBufferEventsI3D)
	DEFINE_WGL_FUNCTION(PFNWGLCREATEIMAGEBUFFERI3DPROC,          wglCreateImageBufferI3D)
	DEFINE_WGL_FUNCTION(PFNWGLDESTROYIMAGEBUFFERI3DPROC,         wglDestroyImageBufferI3D)
	DEFINE_WGL_FUNCTION(PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC,   wglReleaseImageBufferEventsI3D)
#endif

#ifdef WGL_I3D_swap_frame_lock
	DEFINE_WGL_FUNCTION(PFNWGLDISABLEFRAMELOCKI3DPROC,     wglDisableFrameLockI3D)
	DEFINE_WGL_FUNCTION(PFNWGLENABLEFRAMELOCKI3DPROC,      wglEnableFrameLockI3D)
	DEFINE_WGL_FUNCTION(PFNWGLISENABLEDFRAMELOCKI3DPROC,   wglIsEnabledFrameLockI3D)
	DEFINE_WGL_FUNCTION(PFNWGLQUERYFRAMELOCKMASTERI3DPROC, wglQueryFrameLockMasterI3D)
#endif

#ifdef WGL_I3D_swap_frame_usage
	DEFINE_WGL_FUNCTION(PFNWGLBEGINFRAMETRACKINGI3DPROC, wglBeginFrameTrackingI3D)
	DEFINE_WGL_FUNCTION(PFNWGLENDFRAMETRACKINGI3DPROC,   wglEndFrameTrackingI3D)
	DEFINE_WGL_FUNCTION(PFNWGLGETFRAMEUSAGEI3DPROC,      wglGetFrameUsageI3D)
	DEFINE_WGL_FUNCTION(PFNWGLQUERYFRAMETRACKINGI3DPROC, wglQueryFrameTrackingI3D)
#endif

#ifdef WGL_NV_DX_interop
	DEFINE_WGL_FUNCTION(PFNWGLDXCLOSEDEVICENVPROC,            wglDXCloseDeviceNV)
	DEFINE_WGL_FUNCTION(PFNWGLDXLOCKOBJECTSNVPROC,            wglDXLockObjectsNV)
	DEFINE_WGL_FUNCTION(PFNWGLDXOBJECTACCESSNVPROC,           wglDXObjectAccessNV)
	DEFINE_WGL_FUNCTION(PFNWGLDXOPENDEVICENVPROC,             wglDXOpenDeviceNV)
	DEFINE_WGL_FUNCTION(PFNWGLDXREGISTEROBJECTNVPROC,         wglDXRegisterObjectNV)
	DEFINE_WGL_FUNCTION(PFNWGLDXSETRESOURCESHAREHANDLENVPROC, wglDXSetResourceShareHandleNV)
	DEFINE_WGL_FUNCTION(PFNWGLDXUNLOCKOBJECTSNVPROC,          wglDXUnlockObjectsNV)
	DEFINE_WGL_FUNCTION(PFNWGLDXUNREGISTEROBJECTNVPROC,       wglDXUnregisterObjectNV)
#endif

#ifdef WGL_NV_copy_image
	DEFINE_WGL_FUNCTION(PFNWGLCOPYIMAGESUBDATANVPROC, wglCopyImageSubDataNV)
#endif

#ifdef WGL_NV_delay_before_swap
	DEFINE_WGL_FUNCTION(PFNWGLDELAYBEFORESWAPNVPROC, wglDelayBeforeSwapNV)
#endif

#ifdef WGL_NV_gpu_affinity
	DEFINE_WGL_FUNCTION(PFNWGLCREATEAFFINITYDCNVPROC,       wglCreateAffinityDCNV)
	DEFINE_WGL_FUNCTION(PFNWGLDELETEDCNVPROC,               wglDeleteDCNV)
	DEFINE_WGL_FUNCTION(PFNWGLENUMGPUDEVICESNVPROC,         wglEnumGpuDevicesNV)
	DEFINE_WGL_FUNCTION(PFNWGLENUMGPUSFROMAFFINITYDCNVPROC, wglEnumGpusFromAffinityDCNV)
	DEFINE_WGL_FUNCTION(PFNWGLENUMGPUSNVPROC,               wglEnumGpusNV)
#endif

#ifdef WGL_NV_present_video
	DEFINE_WGL_FUNCTION(PFNWGLBINDVIDEODEVICENVPROC,       wglBindVideoDeviceNV)
	DEFINE_WGL_FUNCTION(PFNWGLENUMERATEVIDEODEVICESNVPROC, wglEnumerateVideoDevicesNV)
	DEFINE_WGL_FUNCTION(PFNWGLQUERYCURRENTCONTEXTNVPROC,   wglQueryCurrentContextNV)
#endif

#ifdef WGL_NV_swap_group
	DEFINE_WGL_FUNCTION(PFNWGLBINDSWAPBARRIERNVPROC,    wglBindSwapBarrierNV)
	DEFINE_WGL_FUNCTION(PFNWGLJOINSWAPGROUPNVPROC,      wglJoinSwapGroupNV)
	DEFINE_WGL_FUNCTION(PFNWGLQUERYFRAMECOUNTNVPROC,    wglQueryFrameCountNV)
	DEFINE_WGL_FUNCTION(PFNWGLQUERYMAXSWAPGROUPSNVPROC, wglQueryMaxSwapGroupsNV)
	DEFINE_WGL_FUNCTION(PFNWGLQUERYSWAPGROUPNVPROC,     wglQuerySwapGroupNV)
	DEFINE_WGL_FUNCTION(PFNWGLRESETFRAMECOUNTNVPROC,    wglResetFrameCountNV)
#endif

#ifdef WGL_NV_vertex_array_range
	DEFINE_WGL_FUNCTION(PFNWGLALLOCATEMEMORYNVPROC, wglAllocateMemoryNV)
	DEFINE_WGL_FUNCTION(PFNWGLFREEMEMORYNVPROC,     wglFreeMemoryNV)
#endif

#ifdef WGL_NV_video_capture
	DEFINE_WGL_FUNCTION(PFNWGLBINDVIDEOCAPTUREDEVICENVPROC,       wglBindVideoCaptureDeviceNV)
	DEFINE_WGL_FUNCTION(PFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC, wglEnumerateVideoCaptureDevicesNV)
	DEFINE_WGL_FUNCTION(PFNWGLLOCKVIDEOCAPTUREDEVICENVPROC,       wglLockVideoCaptureDeviceNV)
	DEFINE_WGL_FUNCTION(PFNWGLQUERYVIDEOCAPTUREDEVICENVPROC,      wglQueryVideoCaptureDeviceNV)
	DEFINE_WGL_FUNCTION(PFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC,    wglReleaseVideoCaptureDeviceNV)
#endif

#ifdef WGL_NV_video_output
	DEFINE_WGL_FUNCTION(PFNWGLBINDVIDEOIMAGENVPROC,     wglBindVideoImageNV)
	DEFINE_WGL_FUNCTION(PFNWGLGETVIDEODEVICENVPROC,     wglGetVideoDeviceNV)
	DEFINE_WGL_FUNCTION(PFNWGLGETVIDEOINFONVPROC,       wglGetVideoInfoNV)
	DEFINE_WGL_FUNCTION(PFNWGLRELEASEVIDEODEVICENVPROC, wglReleaseVideoDeviceNV)
	DEFINE_WGL_FUNCTION(PFNWGLRELEASEVIDEOIMAGENVPROC,  wglReleaseVideoImageNV)
	DEFINE_WGL_FUNCTION(PFNWGLSENDPBUFFERTOVIDEONVPROC, wglSendPbufferToVideoNV)
#endif

#ifdef WGL_OML_sync_control
	DEFINE_WGL_FUNCTION(PFNWGLGETMSCRATEOMLPROC,          wglGetMscRateOML)
	DEFINE_WGL_FUNCTION(PFNWGLGETSYNCVALUESOMLPROC,       wglGetSyncValuesOML)
	DEFINE_WGL_FUNCTION(PFNWGLSWAPBUFFERSMSCOMLPROC,      wglSwapBuffersMscOML)
	DEFINE_WGL_FUNCTION(PFNWGLSWAPLAYERBUFFERSMSCOMLPROC, wglSwapLayerBuffersMscOML)
	DEFINE_WGL_FUNCTION(PFNWGLWAITFORMSCOMLPROC,          wglWaitForMscOML)
	DEFINE_WGL_FUNCTION(PFNWGLWAITFORSBCOMLPROC,          wglWaitForSbcOML)
#endif
}